import 'package:drift/drift.dart';
import 'package:injectable/injectable.dart';
import 'package:msiglife_test/data/model/meal_data/meal_data_model.dart';
import 'package:msiglife_test/data/repository/source/local/meal_local.dart';
import 'package:msiglife_test/domain/entity/meal_data/meal_data.dart';

@injectable
class MealDataMapper {
  MealDataEntity fromModelToEntity(MealDataModel model) {
    return MealDataEntity(
      idMeal: model.idMeal ?? '',
      strArea: model.strArea ?? '',
      strCategory: model.strCategory ?? '',
      strDrinkAlternate: model.strDrinkAlternate ?? '',
      strIngredient10: model.strIngredient10 ?? '',
      strIngredient11: model.strIngredient11 ?? '',
      strIngredient12: model.strIngredient12 ?? '',
      strIngredient13: model.strIngredient13 ?? '',
      strIngredient14: model.strIngredient14 ?? '',
      strIngredient15: model.strIngredient15 ?? '',
      strIngredient16: model.strIngredient16 ?? '',
      strIngredient17: model.strIngredient17 ?? '',
      strIngredient18: model.strIngredient18 ?? '',
      strIngredient19: model.strIngredient19 ?? '',
      strIngredient1: model.strIngredient1 ?? '',
      strIngredient20: model.strIngredient20 ?? '',
      strIngredient2: model.strIngredient2 ?? '',
      strIngredient3: model.strIngredient3 ?? '',
      strIngredient4: model.strIngredient4 ?? '',
      strIngredient5: model.strIngredient5 ?? '',
      strIngredient6: model.strIngredient6 ?? '',
      strIngredient7: model.strIngredient7 ?? '',
      strIngredient8: model.strIngredient8 ?? '',
      strIngredient9: model.strIngredient9 ?? '',
      strInstructions: model.strInstructions ?? '',
      strMeal: model.strMeal ?? '',
      strMealThumb: model.strMealThumb ?? '',
      strMeasure10: model.strMeasure10 ?? '',
      strMeasure11: model.strMeasure11 ?? '',
      strMeasure12: model.strMeasure12 ?? '',
      strMeasure13: model.strMeasure13 ?? '',
      strMeasure14: model.strMeasure14 ?? '',
      strMeasure15: model.strMeasure15 ?? '',
      strMeasure16: model.strMeasure16 ?? '',
      strMeasure17: model.strMeasure17 ?? '',
      strMeasure18: model.strMeasure18 ?? '',
      strMeasure19: model.strMeasure19 ?? '',
      strMeasure1: model.strMeasure1 ?? '',
      strMeasure20: model.strMeasure20 ?? '',
      strMeasure2: model.strMeasure2 ?? '',
      strMeasure3: model.strMeasure3 ?? '',
      strMeasure4: model.strMeasure4 ?? '',
      strMeasure5: model.strMeasure5 ?? '',
      strMeasure6: model.strMeasure6 ?? '',
      strMeasure7: model.strMeasure7 ?? '',
      strMeasure8: model.strMeasure8 ?? '',
      strMeasure9: model.strMeasure9 ?? '',
      strTags: model.strTags ?? '',
      strYoutube: model.strYoutube ?? '',
      strSource: model.strSource ?? '',
      strImageSource: model.strImageSource ?? '',
      strCreativeCommonsConfirmed: model.strCreativeCommonsConfirmed ?? '',
      dateModified: model.dateModified ?? '',
    );
  }

  MealDataModel fromEntityToModel(MealDataEntity entity) {
    return MealDataModel(
      idMeal: entity.idMeal,
      strArea: entity.strArea,
      strCategory: entity.strCategory,
      strDrinkAlternate: entity.strDrinkAlternate,
      strIngredient10: entity.strIngredient10,
      strIngredient11: entity.strIngredient11,
      strIngredient12: entity.strIngredient12,
      strIngredient13: entity.strIngredient13,
      strIngredient14: entity.strIngredient14,
      strIngredient15: entity.strIngredient15,
      strIngredient16: entity.strIngredient16,
      strIngredient17: entity.strIngredient17,
      strIngredient18: entity.strIngredient18,
      strIngredient19: entity.strIngredient19,
      strIngredient1: entity.strIngredient1,
      strIngredient20: entity.strIngredient20,
      strIngredient2: entity.strIngredient2,
      strIngredient3: entity.strIngredient3,
      strIngredient4: entity.strIngredient4,
      strIngredient5: entity.strIngredient5,
      strIngredient6: entity.strIngredient6,
      strIngredient7: entity.strIngredient7,
      strIngredient8: entity.strIngredient8,
      strIngredient9: entity.strIngredient9,
      strInstructions: entity.strInstructions,
      strMeal: entity.strMeal,
      strMealThumb: entity.strMealThumb,
      strMeasure2: entity.strMeasure2,
      strMeasure3: entity.strMeasure3,
      strMeasure4: entity.strMeasure4,
      strMeasure5: entity.strMeasure5,
      strMeasure6: entity.strMeasure6,
      strMeasure7: entity.strMeasure7,
      strMeasure8: entity.strMeasure8,
      strMeasure9: entity.strMeasure9,
      strMeasure10: entity.strMeasure10,
      strMeasure11: entity.strMeasure11,
      strMeasure12: entity.strMeasure12,
      strMeasure13: entity.strMeasure13,
      strMeasure14: entity.strMeasure14,
      strMeasure15: entity.strMeasure15,
      strMeasure16: entity.strMeasure16,
      strMeasure17: entity.strMeasure17,
      strMeasure18: entity.strMeasure18,
      strMeasure19: entity.strMeasure19,
      strMeasure1: entity.strMeasure1,
      strMeasure20: entity.strMeasure20,
      strTags: entity.strTags,
      strYoutube: entity.strYoutube,
      strSource: entity.strSource,
      strImageSource: entity.strImageSource,
      strCreativeCommonsConfirmed: entity.strCreativeCommonsConfirmed,
      dateModified: entity.dateModified,
    );
  }

  MealDataDbCompanion fromEntityToDb(MealDataEntity entity) {
    return MealDataDbCompanion(
      idMeal: Value(entity.idMeal),
      strArea: Value(entity.strArea),
      strCategory: Value(entity.strCategory),
      strDrinkAlternate: Value(entity.strDrinkAlternate),
      strIngredient10: Value(entity.strIngredient10),
      strIngredient11: Value(entity.strIngredient11),
      strIngredient12: Value(entity.strIngredient12),
      strIngredient13: Value(entity.strIngredient13),
      strIngredient14: Value(entity.strIngredient14),
      strIngredient15: Value(entity.strIngredient15),
      strIngredient16: Value(entity.strIngredient16),
      strIngredient17: Value(entity.strIngredient17),
      strIngredient18: Value(entity.strIngredient18),
      strIngredient19: Value(entity.strIngredient19),
      strIngredient1: Value(entity.strIngredient1),
      strIngredient20: Value(entity.strIngredient20),
      strIngredient2: Value(entity.strIngredient2),
      strIngredient3: Value(entity.strIngredient3),
      strIngredient4: Value(entity.strIngredient4),
      strIngredient5: Value(entity.strIngredient5),
      strIngredient6: Value(entity.strIngredient6),
      strIngredient7: Value(entity.strIngredient7),
      strIngredient8: Value(entity.strIngredient8),
      strIngredient9: Value(entity.strIngredient9),
      strInstructions: Value(entity.strInstructions),
      strMeal: Value(entity.strMeal),
      strMealThumb: Value(entity.strMealThumb),
      strMeasure2: Value(entity.strMeasure2),
      strMeasure3: Value(entity.strMeasure3),
      strMeasure4: Value(entity.strMeasure4),
      strMeasure5: Value(entity.strMeasure5),
      strMeasure6: Value(entity.strMeasure6),
      strMeasure7: Value(entity.strMeasure7),
      strMeasure8: Value(entity.strMeasure8),
      strMeasure9: Value(entity.strMeasure9),
      strMeasure10: Value(entity.strMeasure10),
      strMeasure11: Value(entity.strMeasure11),
      strMeasure12: Value(entity.strMeasure12),
      strMeasure13: Value(entity.strMeasure13),
      strMeasure14: Value(entity.strMeasure14),
      strMeasure15: Value(entity.strMeasure15),
      strMeasure16: Value(entity.strMeasure16),
      strMeasure17: Value(entity.strMeasure17),
      strMeasure18: Value(entity.strMeasure18),
      strMeasure19: Value(entity.strMeasure19),
      strMeasure1: Value(entity.strMeasure1),
      strMeasure20: Value(entity.strMeasure20),
      strTags: Value(entity.strTags),
      strYoutube: Value(entity.strYoutube),
      strSource: Value(entity.strSource),
      strImageSource: Value(entity.strImageSource),
      strCreativeCommonsConfirmed: Value(entity.strCreativeCommonsConfirmed),
      dateModified: Value(entity.dateModified),
    );
  }

  MealDataEntity fromDbToEntity(MealDataDbData db) {
    return MealDataEntity(
      idMeal: db.idMeal,
      strArea: db.strArea,
      strCategory: db.strCategory,
      strDrinkAlternate: db.strDrinkAlternate,
      strIngredient10: db.strIngredient10,
      strIngredient11: db.strIngredient11,
      strIngredient12: db.strIngredient12,
      strIngredient13: db.strIngredient13,
      strIngredient14: db.strIngredient14,
      strIngredient15: db.strIngredient15,
      strIngredient16: db.strIngredient16,
      strIngredient17: db.strIngredient17,
      strIngredient18: db.strIngredient18,
      strIngredient19: db.strIngredient19,
      strIngredient1: db.strIngredient1,
      strIngredient20: db.strIngredient20,
      strIngredient2: db.strIngredient2,
      strIngredient3: db.strIngredient3,
      strIngredient4: db.strIngredient4,
      strIngredient5: db.strIngredient5,
      strIngredient6: db.strIngredient6,
      strIngredient7: db.strIngredient7,
      strIngredient8: db.strIngredient8,
      strIngredient9: db.strIngredient9,
      strInstructions: db.strInstructions,
      strMeal: db.strMeal,
      strMealThumb: db.strMealThumb,
      strMeasure2: db.strMeasure2,
      strMeasure3: db.strMeasure3,
      strMeasure4: db.strMeasure4,
      strMeasure5: db.strMeasure5,
      strMeasure6: db.strMeasure6,
      strMeasure7: db.strMeasure7,
      strMeasure8: db.strMeasure8,
      strMeasure9: db.strMeasure9,
      strMeasure10: db.strMeasure10,
      strMeasure11: db.strMeasure11,
      strMeasure12: db.strMeasure12,
      strMeasure13: db.strMeasure13,
      strMeasure14: db.strMeasure14,
      strMeasure15: db.strMeasure15,
      strMeasure16: db.strMeasure16,
      strMeasure17: db.strMeasure17,
      strMeasure18: db.strMeasure18,
      strMeasure19: db.strMeasure19,
      strMeasure1: db.strMeasure1,
      strMeasure20: db.strMeasure20,
      strTags: db.strTags,
      strYoutube: db.strYoutube,
      strSource: db.strSource,
      strImageSource: db.strImageSource,
      strCreativeCommonsConfirmed: db.strCreativeCommonsConfirmed,
      dateModified: db.dateModified,
    );
  }
}
