import 'package:injectable/injectable.dart';
import 'package:msiglife_test/data/model/meal_data/meal_data_model.dart';
import 'package:msiglife_test/domain/entity/meal_data/meal_data.dart';

@injectable
class MealDataMapper {
  MealDataEntity toEntity(MealDataModel model) {
    return MealDataEntity(
      idMeal: model.idMeal ?? '',
      strArea: model.strArea ?? '',
      strCategory: model.strCategory ?? '',
      strDrinkAlternate: model.strDrinkAlternate ?? '',
      strIngredient10: model.strIngredient10 ?? '',
      strIngredient11: model.strIngredient11 ?? '',
      strIngredient12: model.strIngredient12 ?? '',
      strIngredient13: model.strIngredient13 ?? '',
      strIngredient14: model.strIngredient14 ?? '',
      strIngredient15: model.strIngredient15 ?? '',
      strIngredient16: model.strIngredient16 ?? '',
      strIngredient17: model.strIngredient17 ?? '',
      strIngredient18: model.strIngredient18 ?? '',
      strIngredient19: model.strIngredient19 ?? '',
      strIngredient1: model.strIngredient1 ?? '',
      strIngredient20: model.strIngredient20 ?? '',
      strIngredient2: model.strIngredient2 ?? '',
      strIngredient3: model.strIngredient3 ?? '',
      strIngredient4: model.strIngredient4 ?? '',
      strIngredient5: model.strIngredient5 ?? '',
      strIngredient6: model.strIngredient6 ?? '',
      strIngredient7: model.strIngredient7 ?? '',
      strIngredient8: model.strIngredient8 ?? '',
      strIngredient9: model.strIngredient9 ?? '',
      strInstructions: model.strInstructions ?? '',
      strMeal: model.strMeal ?? '',
      strMealThumb: model.strMealThumb ?? '',
      strMeasure10: model.strMeasure10 ?? '',
      strMeasure11: model.strMeasure11 ?? '',
      strMeasure12: model.strMeasure12 ?? '',
      strMeasure13: model.strMeasure13 ?? '',
      strMeasure14: model.strMeasure14 ?? '',
      strMeasure15: model.strMeasure15 ?? '',
      strMeasure16: model.strMeasure16 ?? '',
      strMeasure17: model.strMeasure17 ?? '',
      strMeasure18: model.strMeasure18 ?? '',
      strMeasure19: model.strMeasure19 ?? '',
      strMeasure1: model.strMeasure1 ?? '',
      strMeasure20: model.strMeasure20 ?? '',
      strMeasure2: model.strMeasure2 ?? '',
      strMeasure3: model.strMeasure3 ?? '',
      strMeasure4: model.strMeasure4 ?? '',
      strMeasure5: model.strMeasure5 ?? '',
      strMeasure6: model.strMeasure6 ?? '',
      strMeasure7: model.strMeasure7 ?? '',
      strMeasure8: model.strMeasure8 ?? '',
      strMeasure9: model.strMeasure9 ?? '',
      strTags: model.strTags ?? '',
      strYoutube: model.strYoutube ?? '',
      strSource: model.strSource ?? '',
      strImageSource: model.strImageSource ?? '',
      strCreativeCommonsConfirmed: model.strCreativeCommonsConfirmed ?? '',
      dateModified: model.dateModified ?? '',
    );
  }

  MealDataModel toModel(MealDataEntity entity) {
    return MealDataModel(
      idMeal: entity.idMeal,
      strArea: entity.strArea,
      strCategory: entity.strCategory,
      strDrinkAlternate: entity.strDrinkAlternate,
      strIngredient10: entity.strIngredient10,
      strIngredient11: entity.strIngredient11,
      strIngredient12: entity.strIngredient12,
      strIngredient13: entity.strIngredient13,
      strIngredient14: entity.strIngredient14,
      strIngredient15: entity.strIngredient15,
      strIngredient16: entity.strIngredient16,
      strIngredient17: entity.strIngredient17,
      strIngredient18: entity.strIngredient18,
      strIngredient19: entity.strIngredient19,
      strIngredient1: entity.strIngredient1,
      strIngredient20: entity.strIngredient20,
      strIngredient2: entity.strIngredient2,
      strIngredient3: entity.strIngredient3,
      strIngredient4: entity.strIngredient4,
      strIngredient5: entity.strIngredient5,
      strIngredient6: entity.strIngredient6,
      strIngredient7: entity.strIngredient7,
      strIngredient8: entity.strIngredient8,
      strIngredient9: entity.strIngredient9,
      strInstructions: entity.strInstructions,
      strMeal: entity.strMeal,
      strMealThumb: entity.strMealThumb,
      strMeasure2: entity.strMeasure2,
      strMeasure3: entity.strMeasure3,
      strMeasure4: entity.strMeasure4,
      strMeasure5: entity.strMeasure5,
      strMeasure6: entity.strMeasure6,
      strMeasure7: entity.strMeasure7,
      strMeasure8: entity.strMeasure8,
      strMeasure9: entity.strMeasure9,
      strMeasure10: entity.strMeasure10,
      strMeasure11: entity.strMeasure11,
      strMeasure12: entity.strMeasure12,
      strMeasure13: entity.strMeasure13,
      strMeasure14: entity.strMeasure14,
      strMeasure15: entity.strMeasure15,
      strMeasure16: entity.strMeasure16,
      strMeasure17: entity.strMeasure17,
      strMeasure18: entity.strMeasure18,
      strMeasure19: entity.strMeasure19,
      strMeasure1: entity.strMeasure1,
      strMeasure20: entity.strMeasure20,
      strTags: entity.strTags,
      strYoutube: entity.strYoutube,
      strSource: entity.strSource,
      strImageSource: entity.strImageSource,
      strCreativeCommonsConfirmed: entity.strCreativeCommonsConfirmed,
      dateModified: entity.dateModified,
    );
  }
}
